/*
 * The README's animated art: a title banner and a drawn round trip, each in a light
 * and a dark variant that the README pairs through <picture>.
 *
 * GitHub renders README markdown with no CSS or JavaScript of its own, but an SVG
 * referenced as an image is drawn by the browser as a self-contained document, so the
 * <style> and @keyframes inside it run. That is the only motion a README can have, and
 * it is all here. No external fonts or images: an SVG loaded as <img> cannot fetch.
 *
 *   pnpm readme:art     → assets/readme-{hero,loop}{,-dark}.svg
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Theme = {
  ink: string
  ink2: string
  add: string
  del: string
  ground: string // GitHub's page colour, for the cut-out in the comment dot
}

const light: Theme = {
  ink: '#1f2328',
  ink2: '#59636e',
  add: '#1a7f37',
  del: '#cf222e',
  ground: '#ffffff',
}
const dark: Theme = {
  ink: '#f0f6fc',
  ink2: '#9198a1',
  add: '#3fb950',
  del: '#f85149',
  ground: '#0d1117',
}

const SANS = `-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif`
const MONO = `ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace`
const EASE = 'cubic-bezier(0.2, 0.7, 0.2, 1)'

function escapeXml(text: string) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/* ── The banner ───────────────────────────────────────────────────────── */

/*
 * Quiet on purpose: no background, so it sits on GitHub's own page, and the only
 * motion is the mark behaving like the diff it is (the same loop as the site's hero).
 */
function hero(t: Theme) {
  const W = 1280
  const H = 196
  const S = 2.6 // the mark's scale: its 32-unit box becomes 83px
  const markX = 506
  const markY = 70 - 16 * S

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="Diffo: the human way to review agent-written code">
  <!-- Generated by scripts/build-readme-art.ts. Edit there, then run pnpm readme:art. -->
  <style>
    .rise { animation: rise 0.9s ${EASE} both; }
    @keyframes rise { from { opacity: 0; transform: translateY(10px); } }
    .mark path { fill: none; stroke-width: 2.6; stroke-linecap: round; stroke: ${t.ink}; }
    .m-del { animation: m-del 9s ease infinite; }
    .m-add { animation: m-add 9s ease infinite; }
    .m-type { stroke-dasharray: 11 11; animation: m-add 9s ease infinite, m-type 9s ${EASE} infinite; }
    .m-comment { opacity: 0; transform-box: fill-box; transform-origin: center; animation: m-comment 9s ${EASE} infinite; }
    @keyframes m-del { 0%, 8% { stroke: ${t.ink}; } 14%, 70% { stroke: ${t.del}; } 80%, 100% { stroke: ${t.ink}; } }
    @keyframes m-add { 0%, 18% { stroke: ${t.ink}; } 24%, 70% { stroke: ${t.add}; } 80%, 100% { stroke: ${t.ink}; } }
    @keyframes m-type { 0%, 46% { stroke-dashoffset: 0; } 52% { stroke-dashoffset: 11; } 62%, 100% { stroke-dashoffset: 0; } }
    @keyframes m-comment { 0%, 28% { opacity: 0; transform: scale(0.4); } 34%, 66% { opacity: 1; transform: none; } 72%, 100% { opacity: 0; transform: scale(0.4); } }
    @media (prefers-reduced-motion: reduce) { * { animation: none !important; } .m-comment { opacity: 0; } }
  </style>

  <g class="rise">
    <g class="mark" transform="translate(${markX} ${markY}) scale(${S})">
      <path class="m-del" d="M5 7.5h4M14 7.5h13"/>
      <path d="M14 15h9"/>
      <path class="m-add" d="M5 22.5h4M7 20.5v4"/>
      <path class="m-type" d="M14 22.5h11"/>
      <g class="m-comment"><circle cx="26.5" cy="12.6" r="3.1" fill="${t.add}"/><path d="M24.9 12.6h3.2M26.5 11v3.2" style="stroke:${t.ground};stroke-width:1.1"/></g>
    </g>
    <text x="${markX + 32 * S + 20}" y="93" font-family="${SANS}" font-size="66" font-weight="700" letter-spacing="-2" fill="${t.ink}">Diffo</text>
  </g>
  <text class="rise" style="animation-delay:0.2s" x="${W / 2}" y="168" text-anchor="middle" font-family="${SANS}" font-size="28" font-weight="500" letter-spacing="-0.4" fill="${t.ink2}">The human way to review agent-written code.</text>
</svg>
`
}

/* ── The round trip, drawn as the app ─────────────────────────────────── */

/*
 * The review UI's own tokens (src/ui/styles.css), so the card reads as Diffo rather
 * than as a generic diff. Same picture as docs/.vitepress/theme/AppReview.vue.
 */
type App = {
  paper: string
  fill: string
  fill2: string
  ink: string
  ink2: string
  ink3: string
  hair: string
  brand: string
  attn: string
  attnWash: string
  attnLine: string
  add: string
  addRow: string
  del: string
  delRow: string
  focus: string
  k: string
  f: string
  n: string
  finishBg: string
  finishFg: string
}

const appLight: App = {
  paper: '#ffffff',
  fill: '#f5f5f7',
  fill2: '#ebebed',
  ink: '#1d1d1f',
  ink2: '#515154',
  ink3: '#6e6e73',
  hair: '#e5e5e7',
  brand: '#1f883d',
  attn: '#9a6206',
  attnWash: '#faf1e2',
  attnLine: '#e6cfa0',
  add: '#248a3d',
  addRow: 'rgba(36,138,61,0.1)',
  del: '#c9252d',
  delRow: 'rgba(201,37,45,0.085)',
  focus: 'rgba(127,127,127,0.1)',
  k: '#cf222e',
  f: '#8250df',
  n: '#0550ae',
  finishBg: '#1d1d1f',
  finishFg: '#ffffff',
}

const appDark: App = {
  paper: '#000000',
  fill: '#1c1c1e',
  fill2: '#2c2c2e',
  ink: '#f5f5f7',
  ink2: '#c7c7cc',
  ink3: '#8e8e93',
  hair: '#2c2c2e',
  brand: '#238636',
  attn: '#e3a646',
  attnWash: 'rgba(227,166,70,0.12)',
  attnLine: 'rgba(227,166,70,0.4)',
  add: '#3fb950',
  addRow: 'rgba(63,185,80,0.13)',
  del: '#f85149',
  delRow: 'rgba(248,81,73,0.12)',
  focus: 'rgba(127,127,127,0.16)',
  k: '#ff7b72',
  f: '#d2a8ff',
  n: '#79c0ff',
  finishBg: '#f5f5f7',
  finishFg: '#000000',
}

type Seg = [kind: '' | 'k' | 'f' | 'n', text: string]

function loop(a: App) {
  const W = 1280
  const RAIL = 250
  const X = RAIL + 20 // file card left
  const XR = W - 24 // file card right
  const ROW = 28
  const CODE_TOP = 166
  const THREAD = CODE_TOP + 4 * ROW + 8 // thread top
  const A_H = 104 // thread: header + your comment
  const B_H = 138 // thread: the agent's row + reply box
  const AFTER = THREAD + A_H + B_H + 10 // first row below the thread, when open
  const LOOP = 12 // seconds
  const H = AFTER + 3 * ROW + 36

  const tone = (k: Seg[0]) => (k === 'k' ? a.k : k === 'f' ? a.f : k === 'n' ? a.n : a.ink)
  const code = (segs: Seg[]) =>
    segs.map(([k, s]) => `<tspan fill="${tone(k)}">${escapeXml(s)}</tspan>`).join('')

  const row = (
    y: number,
    o: number | '',
    n: number | '',
    segs: Seg[],
    kind?: 'add' | 'del',
    extra = '',
  ) => {
    const bg = kind === 'add' ? a.addRow : kind === 'del' ? a.delRow : 'none'
    const sign = kind === 'add' ? '+' : kind === 'del' ? '−' : ''
    const signFill = kind === 'add' ? a.add : a.del
    return `<g${extra}>
      <rect x="${X + 1}" y="${y}" width="${XR - X - 2}" height="${ROW}" fill="${bg}"/>
      ${kind === 'add' ? `<rect x="${X + 88}" y="${y}" width="2" height="${ROW}" fill="${a.add}"/>` : ''}
      <text x="${X + 38}" y="${y + 19}" text-anchor="end" font-family="${MONO}" font-size="13" fill="${a.ink3}">${o}</text>
      <text x="${X + 80}" y="${y + 19}" text-anchor="end" font-family="${MONO}" font-size="13" fill="${a.ink3}">${n}</text>
      <text x="${X + 104}" y="${y + 19}" text-anchor="middle" font-family="${MONO}" font-size="14" fill="${signFill}">${sign}</text>
      <text x="${X + 120}" y="${y + 19}" font-family="${MONO}" font-size="14" xml:space="preserve">${code(segs)}</text>
    </g>`
  }

  const tick = (x: number, y: number, cls: string) => `<g class="${cls}">
      <rect x="${x}" y="${y}" width="14" height="14" rx="3.5" fill="${a.brand}"/>
      <path d="M${x + 3.2} ${y + 7.4}l2.8 2.8 4.8-5.4" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
    </g>`
  const box = (x: number, y: number) =>
    `<rect x="${x + 0.5}" y="${y + 0.5}" width="13" height="13" rx="3.5" fill="none" stroke="${a.ink3}"/>`

  const layers = ['Parse due dates', 'Wire into the list', 'Tests']
    .map((title, i) => {
      const y = 124 + i * 54
      return `<g>
      ${i === 0 ? `<rect x="0" y="${y - 10}" width="${RAIL}" height="52" fill="${a.fill}"/>` : ''}
      ${box(16, y)}
      ${i === 0 ? tick(16, y, 'viewed') : ''}
      <text x="42" y="${y + 12}" font-family="${SANS}" font-size="14" font-weight="500" fill="${a.ink}">${title}</text>
      <rect x="42" y="${y + 24}" width="48" height="2" rx="1" fill="${a.fill2}"/>
      ${i === 0 ? `<rect class="viewed" x="42" y="${y + 24}" width="48" height="2" rx="1" fill="${a.brand}"/>` : ''}
      <text x="98" y="${y + 29}" font-family="${SANS}" font-size="12" fill="${a.ink3}">${[1, 2, 2][i]} file${i ? 's' : ''}</text>
    </g>`
    })
    .join('\n    ')

  const QUESTION = 'Does “friday” on a Friday mean today or next week?'

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="One round trip in the Diffo review: a question goes on line 14, the agent answers in the thread, and the fix lands in the diff">
  <!-- Generated by scripts/build-readme-art.ts. Edit there, then run pnpm readme:art. -->
  <style>
    * { animation-duration: ${LOOP}s; animation-iteration-count: infinite; animation-timing-function: ${EASE}; }
    .focus { animation-name: focus; opacity: 0; }
    @keyframes focus { 0%, 7% { opacity: 0; } 9%, 52% { opacity: 1; } 56%, 100% { opacity: 0; } }
    .lower { animation-name: lower; }
    @keyframes lower {
      0%, 8% { transform: translateY(${-(AFTER - THREAD + 8)}px); }
      11%, 29% { transform: translateY(${-(B_H + 10)}px); }
      32%, 90% { transform: none; }
      95%, 100% { transform: translateY(${-(AFTER - THREAD + 8)}px); }
    }
    .tail { animation-name: tail; }
    @keyframes tail { 0%, 53% { transform: translateY(${-ROW}px); } 56%, 90% { transform: none; } 95%, 100% { transform: translateY(${-ROW}px); } }
    .fix { animation-name: fix; opacity: 0; }
    @keyframes fix { 0%, 54% { opacity: 0; } 57%, 89% { opacity: 1; } 92%, 100% { opacity: 0; } }
    .thread-a { animation-name: thread-a; opacity: 0; }
    @keyframes thread-a { 0%, 8% { opacity: 0; transform: translateY(6px); } 11%, 89% { opacity: 1; transform: none; } 92%, 100% { opacity: 0; } }
    .thread-b { animation-name: thread-b; opacity: 0; }
    @keyframes thread-b { 0%, 29% { opacity: 0; } 32%, 89% { opacity: 1; } 92%, 100% { opacity: 0; } }
    .question { animation-name: question; animation-timing-function: steps(${QUESTION.length}, end); clip-path: inset(0 100% 0 0); }
    @keyframes question { 0%, 11% { clip-path: inset(0 100% 0 0); } 27%, 100% { clip-path: inset(0 0 0 0); } }
    .draft { animation-name: draft; animation-timing-function: steps(1, end); }
    @keyframes draft { 0%, 29% { opacity: 1; } 30%, 100% { opacity: 0; } }
    .sent { animation-name: sent; animation-timing-function: steps(1, end); opacity: 0; }
    @keyframes sent { 0%, 29% { opacity: 0; } 30%, 100% { opacity: 1; } }
    .waiting { animation-name: waiting; animation-timing-function: steps(1, end); opacity: 0; }
    @keyframes waiting { 0%, 31% { opacity: 0; } 32%, 46% { opacity: 1; } 47%, 100% { opacity: 0; } }
    .answered { animation-name: answered; opacity: 0; }
    @keyframes answered { 0%, 46% { opacity: 0; transform: translateY(4px); } 49%, 89% { opacity: 1; transform: none; } 92%, 100% { opacity: 0; } }
    .dots circle { animation: dot 1s ease-in-out infinite; }
    .dots circle:nth-child(2) { animation-delay: 0.15s; }
    .dots circle:nth-child(3) { animation-delay: 0.3s; }
    @keyframes dot { 0%, 100% { opacity: 0.25; } 50% { opacity: 1; } }
    .listening { animation-name: listening; animation-timing-function: steps(1, end); }
    @keyframes listening { 0%, 31% { opacity: 1; } 32%, 47% { opacity: 0; } 48%, 100% { opacity: 1; } }
    .working { animation-name: working; animation-timing-function: steps(1, end); opacity: 0; }
    @keyframes working { 0%, 31% { opacity: 0; } 32%, 47% { opacity: 1; } 48%, 100% { opacity: 0; } }
    .bars rect { animation: eq 0.8s ease-in-out infinite; transform-box: fill-box; transform-origin: center; }
    .bars rect:nth-child(2) { animation-delay: 0.15s; }
    .bars rect:nth-child(3) { animation-delay: 0.3s; }
    @keyframes eq { 50% { transform: scaleY(1.8); } }
    .viewed { animation-name: viewed; }
    @keyframes viewed { 0%, 54% { opacity: 1; } 57%, 92% { opacity: 0; } 96%, 100% { opacity: 1; } }
    .changed { animation-name: changed; opacity: 0; }
    @keyframes changed { 0%, 55% { opacity: 0; transform: translateY(-3px); } 58%, 89% { opacity: 1; transform: none; } 92%, 100% { opacity: 0; } }
    .before { animation-name: before; animation-timing-function: steps(1, end); }
    @keyframes before { 0%, 55% { opacity: 1; } 56%, 91% { opacity: 0; } 92%, 100% { opacity: 1; } }
    .after { animation-name: after; animation-timing-function: steps(1, end); opacity: 0; }
    @keyframes after { 0%, 55% { opacity: 0; } 56%, 91% { opacity: 1; } 92%, 100% { opacity: 0; } }
    @media (prefers-reduced-motion: reduce) {
      * { animation: none !important; }
      .focus, .draft, .waiting, .working, .before { opacity: 0 !important; }
      .fix, .thread-a, .thread-b, .sent, .answered, .changed, .after, .listening { opacity: 1 !important; }
      .question { clip-path: none !important; }
      .lower, .tail { transform: none !important; }
      .viewed { opacity: 0 !important; }
    }
  </style>
  <defs>
    <clipPath id="frame"><rect width="${W}" height="${H}" rx="16"/></clipPath>
    <clipPath id="card"><rect x="${X}" y="112" width="${XR - X}" height="${H - 112 - 20}" rx="10"/></clipPath>
  </defs>

  <g clip-path="url(#frame)">
    <rect width="${W}" height="${H}" fill="${a.paper}"/>

    <!-- Header -->
    <g font-family="${SANS}">
      <path d="M22 22h14M22 28h10M22 34h14" stroke="${a.ink}" stroke-width="1.8" stroke-linecap="round"/>
      <text x="46" y="34" font-size="18" font-weight="600" fill="${a.ink}">Diffo</text>
      <text x="112" y="33" font-family="${MONO}" font-size="13.5" fill="${a.ink3}">todo-app</text>
      <text x="196" y="33" font-family="${MONO}" font-size="13.5" fill="${a.ink3}">⑂ main</text>
      <text x="270" y="33" font-family="${MONO}" font-size="13.5" fill="${a.ink}">working tree → HEAD</text>
      <text x="446" y="33" font-family="${MONO}" font-size="13.5"><tspan fill="${a.add}" class="before">+5</tspan></text>
      <text x="446" y="33" font-family="${MONO}" font-size="13.5"><tspan fill="${a.add}" class="after">+6</tspan></text>
      <text x="472" y="33" font-family="${MONO}" font-size="13.5" fill="${a.del}">−1</text>

      <rect x="960.5" y="14.5" width="160" height="29" rx="14.5" fill="${a.attnWash}" stroke="${a.attnLine}"/>
      <g class="bars" fill="${a.attn}"><rect x="976" y="27" width="2" height="5" rx="1"/><rect x="980" y="25" width="2" height="9" rx="1"/><rect x="984" y="27" width="2" height="5" rx="1"/></g>
      <text class="listening" x="994" y="34" font-size="13" fill="${a.attn}">agent · listening</text>
      <text class="working" x="994" y="34" font-size="13" fill="${a.attn}">agent · working</text>

      <rect x="1134" y="13" width="124" height="32" rx="16" fill="${a.finishBg}"/>
      <text x="1196" y="34" text-anchor="middle" font-size="13.5" font-weight="600" fill="${a.finishFg}">Finish review</text>
    </g>
    <path d="M0 56.5h${W}" stroke="${a.hair}"/>

    <!-- Rail -->
    <path d="M${RAIL + 0.5} 57v${H}" stroke="${a.hair}"/>
    <rect x="10" y="68" width="${RAIL - 20}" height="32" rx="8" fill="${a.fill}"/>
    <rect x="${10 + ((RAIL - 24) * 2) / 3 + 2}" y="70" width="${(RAIL - 24) / 3}" height="28" rx="6" fill="${a.paper}"/>
    <g font-family="${SANS}" font-size="13" text-anchor="middle">
      <text x="${10 + (RAIL - 20) / 6}" y="89" fill="${a.ink3}">Files 3</text>
      <text x="${10 + (RAIL - 20) / 2}" y="89" fill="${a.ink3}">Threads 1</text>
      <text x="${10 + ((RAIL - 20) * 5) / 6}" y="89" fill="${a.ink}">Layers 3</text>
    </g>
    ${layers}

    <!-- Reading pane -->
    <rect x="${X}" y="84" width="56" height="2" rx="1" fill="${a.fill2}"/>
    <rect class="viewed" x="${X}" y="84" width="20" height="2" rx="1" fill="${a.brand}"/>
    <text x="${X + 70}" y="90" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">layer 1 / 3 · 1 file</text>

    <g clip-path="url(#card)">
      <rect x="${X}" y="112" width="${XR - X}" height="${H}" fill="${a.paper}"/>
      <rect x="${X}" y="112" width="${XR - X}" height="46" fill="${a.fill}"/>
      <path d="M${X} 158.5h${XR - X}" stroke="${a.hair}"/>
      <path d="M${X + 16} 131l4 4 4-4" fill="none" stroke="${a.ink3}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
      <text x="${X + 34}" y="140" font-family="${MONO}" font-size="14" fill="${a.ink3}">src/todo/<tspan font-weight="700" fill="${a.ink}">dates.ts</tspan></text>
      <g class="changed">
        <rect x="${X + 200.5}" y="124.5" width="190" height="23" rx="11.5" fill="${a.attnWash}" stroke="${a.attnLine}"/>
        <text x="${X + 295}" y="140" text-anchor="middle" font-family="${SANS}" font-size="12.5" fill="${a.attn}">changed since you read it</text>
      </g>
      <text x="${XR - 232}" y="140" font-family="${MONO}" font-size="13"><tspan class="before" fill="${a.add}">+1</tspan></text>
      <text x="${XR - 232}" y="140" font-family="${MONO}" font-size="13"><tspan class="after" fill="${a.add}">+2</tspan></text>
      <text x="${XR - 208}" y="140" font-family="${MONO}" font-size="13" fill="${a.del}">−1</text>
      <g>${[a.add, a.add, a.add, a.del, a.fill2].map((c, i) => `<rect x="${XR - 180 + i * 10}" y="131" width="8" height="8" rx="1.5" fill="${c}"/>`).join('')}</g>
      <rect x="${XR - 116.5}" y="122.5" width="102" height="27" rx="6" fill="${a.paper}" stroke="${a.hair}"/>
      ${box(XR - 106, 129)}
      ${tick(XR - 106, 129, 'viewed')}
      <text x="${XR - 84}" y="141" font-family="${SANS}" font-size="13.5" fill="${a.ink}">Viewed</text>

      ${row(CODE_TOP, 12, 12, [
        ['k', 'export function '],
        ['f', 'parseDue'],
        ['', '(input: '],
        ['k', 'string'],
        ['', '): Date | '],
        ['k', 'null'],
        ['', ' {'],
      ])}
      ${row(
        CODE_TOP + ROW,
        13,
        '',
        [
          ['k', '  const '],
          ['', 'day = WEEKDAYS.'],
          ['f', 'indexOf'],
          ['', '(input.'],
          ['f', 'toLowerCase'],
          ['', '())'],
        ],
        'del',
      )}
      ${row(
        CODE_TOP + 2 * ROW,
        '',
        13,
        [
          ['k', '  const '],
          ['', 'day = WEEKDAYS.'],
          ['f', 'indexOf'],
          ['', '('],
          ['f', 'normalize'],
          ['', '(input))'],
        ],
        'add',
      )}
      <rect class="focus" x="${X + 1}" y="${CODE_TOP + 3 * ROW}" width="${XR - X - 2}" height="${ROW}" fill="${a.focus}"/>
      ${row(CODE_TOP + 3 * ROW, 14, 14, [
        ['k', '  if '],
        ['', '(day === '],
        ['n', '-1'],
        ['', ') '],
        ['k', 'return null'],
      ])}

      <!-- Thread: the agent's half first, so the comment card's corners sit under it -->
      <g class="thread-b" font-family="${SANS}">
        <path d="M${X + 20.5} ${THREAD + A_H - 12}V${THREAD + A_H + B_H - 10}a10 10 0 0 0 10 10H${XR - 30.5}a10 10 0 0 0 10 -10V${THREAD + A_H - 12}" fill="${a.paper}" stroke="${a.hair}"/>
        <rect x="${X + 21}" y="${THREAD + A_H - 12}" width="${XR - X - 42}" height="12" fill="${a.paper}"/>
        <path d="M${X + 21} ${THREAD + A_H + 0.5}h${XR - X - 42}" stroke="${a.hair}"/>
        <circle cx="${X + 46}" cy="${THREAD + A_H + 26}" r="12" fill="${a.attnWash}" stroke="${a.attnLine}"/>
        <text x="${X + 46}" y="${THREAD + A_H + 31}" text-anchor="middle" font-size="12" fill="${a.attn}">✦</text>
        <text x="${X + 68}" y="${THREAD + A_H + 24}" font-size="13" fill="${a.ink3}"><tspan font-weight="600" fill="${a.attn}">Agent</tspan><tspan class="waiting" dx="6">with the agent · just now</tspan></text>
        <text class="answered" x="${X + 112}" y="${THREAD + A_H + 24}" font-size="13" fill="${a.ink3}">answered in 4.2s</text>
        <g class="waiting dots" fill="${a.ink3}"><circle cx="${X + 72}" cy="${THREAD + A_H + 46}" r="3"/><circle cx="${X + 83}" cy="${THREAD + A_H + 46}" r="3"/><circle cx="${X + 94}" cy="${THREAD + A_H + 46}" r="3"/></g>
        <g class="answered" font-size="14.5" fill="${a.ink}">
          <text x="${X + 68}" y="${THREAD + A_H + 47}">Today, which is wrong: a bare weekday should mean the next one. Fixed, so</text>
          <text x="${X + 68}" y="${THREAD + A_H + 69}"><tspan font-family="${MONO}" font-size="13.5" fill="${a.ink2}">parseDue('friday')</tspan> on a Friday rolls to next week.</text>
        </g>
        <path d="M${X + 21} ${THREAD + A_H + 84.5}h${XR - X - 42}" stroke="${a.hair}"/>
        <rect x="${X + 34.5}" y="${THREAD + A_H + 96.5}" width="${XR - X - 170}" height="30" rx="7" fill="${a.paper}" stroke="${a.hair}"/>
        <text x="${X + 48}" y="${THREAD + A_H + 116}" font-size="13.5" fill="${a.ink3}">Reply…</text>
        <text x="${XR - 90}" y="${THREAD + A_H + 116}" font-size="13.5" fill="${a.ink2}">Resolve</text>
      </g>
      <g class="thread-a" font-family="${SANS}">
        <rect x="${X + 20.5}" y="${THREAD + 0.5}" width="${XR - X - 41}" height="${A_H}" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
        <path d="M${X + 21} ${THREAD + 36}V${THREAD + 10}a10 10 0 0 1 10 -10H${XR - 31}a10 10 0 0 1 10 10V${THREAD + 36}z" fill="${a.fill}"/>
        <path d="M${X + 21} ${THREAD + 36.5}h${XR - X - 42}" stroke="${a.hair}"/>
        <path d="M${X + 36} ${THREAD + 16}l3.5 3.5 3.5-3.5" fill="none" stroke="${a.ink3}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <text x="${X + 52}" y="${THREAD + 23}" font-size="13" fill="${a.ink2}">Comment on line 14</text>
        <rect x="${X + 182.5}" y="${THREAD + 8.5}" width="70" height="20" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
        <text x="${X + 217.5}" y="${THREAD + 22.5}" text-anchor="middle" font-size="12" fill="${a.ink}">Question</text>
        <text class="draft" x="${XR - 40}" y="${THREAD + 23}" text-anchor="end" font-size="12.5" fill="${a.ink3}">Draft</text>
        <text class="sent" x="${XR - 40}" y="${THREAD + 23}" text-anchor="end" font-size="12.5" fill="${a.ink3}">Sent</text>
        <circle cx="${X + 46}" cy="${THREAD + 62}" r="12" fill="${a.ink}"/>
        <text x="${X + 68}" y="${THREAD + 60}" font-size="13" fill="${a.ink3}"><tspan font-weight="600" fill="${a.ink}">You</tspan>  commented just now</text>
        <text class="question" x="${X + 68}" y="${THREAD + 83}" font-size="14.5" fill="${a.ink}">${QUESTION}</text>
      </g>

      <!-- Everything under the thread moves as it opens, and again as the fix lands -->
      <g class="lower">
        <g class="fix">${row(
          AFTER,
          '',
          15,
          [
            ['k', '  if '],
            ['', '(day === '],
            ['f', 'today'],
            ['', '()) '],
            ['k', 'return '],
            ['f', 'nextWeek'],
            ['', '(day)'],
          ],
          'add',
        )}</g>
        <g class="tail">
          <g class="before">${row(AFTER + ROW, 15, 15, [
            ['k', '  return '],
            ['f', 'nextWeekday'],
            ['', '(day)'],
          ])}${row(AFTER + 2 * ROW, 16, 16, [['', '}']])}</g>
          <g class="after">${row(AFTER + ROW, 15, 16, [
            ['k', '  return '],
            ['f', 'nextWeekday'],
            ['', '(day)'],
          ])}${row(AFTER + 2 * ROW, 16, 17, [['', '}']])}</g>
        </g>
      </g>
    </g>
    <rect x="${X + 0.5}" y="112.5" width="${XR - X - 1}" height="${H - 112 - 21}" rx="10" fill="none" stroke="${a.hair}"/>
  </g>
  <rect x="0.5" y="0.5" width="${W - 1}" height="${H - 1}" rx="15.5" fill="none" stroke="${a.hair}"/>
</svg>
`
}

const out = join(import.meta.dirname, '..', 'assets')
for (const [suffix, theme] of [
  ['', light],
  ['-dark', dark],
] as const) {
  writeFileSync(join(out, `readme-hero${suffix}.svg`), hero(theme))
  writeFileSync(join(out, `readme-loop${suffix}.svg`), loop(suffix ? appDark : appLight))
}
console.log('wrote assets/readme-{hero,loop}{,-dark}.svg')
