/*
 * The README's animated art: a title banner and a drawn round trip, each in a light
 * and a dark variant that the README pairs through <picture>.
 *
 * GitHub renders README markdown with no CSS or JavaScript of its own, but an SVG
 * referenced as an image is drawn by the browser as a self-contained document, so the
 * <style> and @keyframes inside it run. That is the only motion a README can have, and
 * it is all here. No external fonts or images: an SVG loaded as <img> cannot fetch.
 *
 *   pnpm readme:art     → assets/readme-hero{,-dark}.svg, docs/assets/readme-{demo,layers}{,-dark}.svg
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

type Theme = {
  ink: string
  ink2: string
  add: string
  del: string
  ground: string // GitHub's page colour, for the cut-out in the comment dot
}

const light: Theme = {
  ink: '#1f2328',
  ink2: '#59636e',
  add: '#1a7f37',
  del: '#cf222e',
  ground: '#ffffff',
}
const dark: Theme = {
  ink: '#f0f6fc',
  ink2: '#9198a1',
  add: '#3fb950',
  del: '#f85149',
  ground: '#0d1117',
}

const SANS = `-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif`
const MONO = `ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace`
const EASE = 'cubic-bezier(0.2, 0.7, 0.2, 1)'

function escapeXml(text: string) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/* ── The banner ───────────────────────────────────────────────────────── */

/*
 * Quiet on purpose: no background, so it sits on GitHub's own page, and the only
 * motion is the mark behaving like the diff it is (the same loop as the site's hero).
 */
function hero(t: Theme) {
  const W = 1280
  const H = 196
  const S = 2.6 // the mark's scale: its 32-unit box becomes 83px
  const markX = 506
  const markY = 70 - 16 * S

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="Diffo: the human way to review agent-written code">
  <!-- Generated by scripts/build-readme-art.ts. Edit there, then run pnpm readme:art. -->
  <style>
    .rise { animation: rise 0.9s ${EASE} both; }
    @keyframes rise { from { opacity: 0; transform: translateY(10px); } }
    .mark path { fill: none; stroke-width: 2.6; stroke-linecap: round; stroke: ${t.ink}; }
    .m-del { animation: m-del 9s ease infinite; }
    .m-add { animation: m-add 9s ease infinite; }
    .m-type { stroke-dasharray: 11 11; animation: m-add 9s ease infinite, m-type 9s ${EASE} infinite; }
    .m-comment { opacity: 0; transform-box: fill-box; transform-origin: center; animation: m-comment 9s ${EASE} infinite; }
    @keyframes m-del { 0%, 8% { stroke: ${t.ink}; } 14%, 70% { stroke: ${t.del}; } 80%, 100% { stroke: ${t.ink}; } }
    @keyframes m-add { 0%, 18% { stroke: ${t.ink}; } 24%, 70% { stroke: ${t.add}; } 80%, 100% { stroke: ${t.ink}; } }
    @keyframes m-type { 0%, 46% { stroke-dashoffset: 0; } 52% { stroke-dashoffset: 11; } 62%, 100% { stroke-dashoffset: 0; } }
    @keyframes m-comment { 0%, 28% { opacity: 0; transform: scale(0.4); } 34%, 66% { opacity: 1; transform: none; } 72%, 100% { opacity: 0; transform: scale(0.4); } }
    @media (prefers-reduced-motion: reduce) { * { animation: none !important; } .m-comment { opacity: 0; } }
  </style>

  <g class="rise">
    <g class="mark" transform="translate(${markX} ${markY}) scale(${S})">
      <path class="m-del" d="M5 7.5h4M14 7.5h13"/>
      <path d="M14 15h9"/>
      <path class="m-add" d="M5 22.5h4M7 20.5v4"/>
      <path class="m-type" d="M14 22.5h11"/>
      <g class="m-comment"><circle cx="26.5" cy="12.6" r="3.1" fill="${t.add}"/><path d="M24.9 12.6h3.2M26.5 11v3.2" style="stroke:${t.ground};stroke-width:1.1"/></g>
    </g>
    <text x="${markX + 32 * S + 20}" y="93" font-family="${SANS}" font-size="66" font-weight="700" letter-spacing="-2" fill="${t.ink}">Diffo</text>
  </g>
  <text class="rise" style="animation-delay:0.2s" x="${W / 2}" y="168" text-anchor="middle" font-family="${SANS}" font-size="28" font-weight="500" letter-spacing="-0.4" fill="${t.ink2}">The human way to review agent-written code.</text>
</svg>
`
}

/* ── The demo: the agent's terminal and the review, side by side ──────── */

/*
 * The review UI's own tokens (src/ui/styles.css), so the card reads as Diffo rather
 * than as a generic diff. Same picture as docs/.vitepress/theme/AppReview.vue.
 */
type App = {
  paper: string
  fill: string
  fill2: string
  ink: string
  ink2: string
  ink3: string
  hair: string
  brand: string
  attn: string
  attnWash: string
  attnLine: string
  add: string
  addRow: string
  del: string
  delRow: string
  focus: string
  k: string
  f: string
  n: string
  finishBg: string
  finishFg: string
}

const appLight: App = {
  paper: '#ffffff',
  fill: '#f5f5f7',
  fill2: '#ebebed',
  ink: '#1d1d1f',
  ink2: '#515154',
  ink3: '#6e6e73',
  hair: '#e5e5e7',
  brand: '#1f883d',
  attn: '#9a6206',
  attnWash: '#faf1e2',
  attnLine: '#e6cfa0',
  add: '#248a3d',
  addRow: 'rgba(36,138,61,0.1)',
  del: '#c9252d',
  delRow: 'rgba(201,37,45,0.085)',
  focus: 'rgba(127,127,127,0.1)',
  k: '#cf222e',
  f: '#8250df',
  n: '#0550ae',
  finishBg: '#1d1d1f',
  finishFg: '#ffffff',
}

const appDark: App = {
  paper: '#000000',
  fill: '#1c1c1e',
  fill2: '#2c2c2e',
  ink: '#f5f5f7',
  ink2: '#c7c7cc',
  ink3: '#8e8e93',
  hair: '#2c2c2e',
  brand: '#238636',
  attn: '#e3a646',
  attnWash: 'rgba(227,166,70,0.12)',
  attnLine: 'rgba(227,166,70,0.4)',
  add: '#3fb950',
  addRow: 'rgba(63,185,80,0.13)',
  del: '#f85149',
  delRow: 'rgba(248,81,73,0.12)',
  focus: 'rgba(127,127,127,0.16)',
  k: '#ff7b72',
  f: '#d2a8ff',
  n: '#79c0ff',
  finishBg: '#f5f5f7',
  finishFg: '#000000',
}

type Seg = [kind: '' | 'k' | 'f' | 'n', text: string]

/*
 * The whole loop in one frame: your agent's terminal on the left, the review it opened
 * on the right, and each message visibly crossing between them. `/diffo` opens the
 * review, your question flies to the agent, its answer and fix fly back and land in the
 * diff you are reading.
 *
 * Everything runs on one 16-second clock. CSS keyframes drive what appears and moves;
 * SMIL <animateMotion> carries the messages along their arcs, because that is the one
 * way to move along a path that every browser draws inside an <img>.
 */
const LOOP = 16 // seconds
const RESET = 93 // % of the loop where the scene fades back to its start

/* Terminal palette: Claude Code's, dark in both variants, as a terminal is. */
const TERM = {
  bg: '#0d1117',
  bar: '#161b22',
  line: '#30363d',
  ink: '#e6edf3',
  dim: '#8b949e',
  link: '#a5b4fc',
  claude: '#d97757',
  auto: '#e3b341',
  promptBg: '#262c36',
  addBg: 'rgba(63,185,80,0.18)',
  add: '#56d364',
}

/*
 * What every README scene shares: the stage, the two windows' geometry, the keyframe
 * helpers that put things on the scene's one clock, the connectors that carry a message
 * between the windows, the terminal's chrome, and the SVG around it all.
 */
function kit(a: App, dark: boolean) {
  const W = 1280
  const H = 720
  const PAD = 24
  const TW = 470 // terminal width
  const GAP = 26
  const RX = PAD + TW + GAP // review window left
  const RW = W - PAD - RX // review window width
  const TOP = PAD
  const WH = H - 2 * PAD // window height

  const stage = dark
    ? {
        from: '#0b0f14',
        to: '#0e1a13',
        dot: 'rgba(255,255,255,0.07)',
        glow: 'rgba(63,185,80,0.16)',
      }
    : { from: '#f6f8fa', to: '#eef6f0', dot: 'rgba(31,35,40,0.08)', glow: 'rgba(31,136,61,0.14)' }
  const amber = dark ? '#d29922' : '#bf8700'

  /* ── keyframe helpers ── */
  const css: string[] = []
  let id = 0
  const nextId = () => id++
  // Hidden until `at`% of the loop, then shown until the reset.
  const show = (at: number, from = 'translateY(6px)') => {
    const name = `s${id++}`
    css.push(
      `.${name} { animation-name: ${name}; opacity: 0; }
    @keyframes ${name} { 0%, ${at}% { opacity: 0; transform: ${from}; } ${at + 1.6}%, ${RESET}% { opacity: 1; transform: none; } ${RESET + 3}%, 100% { opacity: 0; transform: none; } }`,
    )
    return name
  }
  // Shown only between `from`% and `to`% of the loop. A negative `from` means "from
  // the start": shown at once, and back again as the scene resets.
  const between = (from: number, to: number) => {
    const name = `b${id++}`
    css.push(
      from < 0
        ? `.${name} { animation-name: ${name}; }
    @keyframes ${name} { 0%, ${to}% { opacity: 1; } ${to + 1}%, ${RESET + 3}% { opacity: 0; } ${RESET + 6}%, 100% { opacity: 1; } }`
        : `.${name} { animation-name: ${name}; opacity: 0; }
    @keyframes ${name} { 0%, ${from}% { opacity: 0; } ${from + 1}%, ${to}% { opacity: 1; } ${to + 1}%, 100% { opacity: 0; } }`,
    )
    return name
  }
  // Swept open left to right, character by character.
  const type = (from: number, to: number, chars: number) => {
    const name = `t${id++}`
    css.push(
      `.${name} { animation-name: ${name}; animation-timing-function: steps(${chars}, end); clip-path: inset(0 100% 0 0); }
    @keyframes ${name} { 0%, ${from}% { clip-path: inset(0 100% 0 0); } ${to}%, 100% { clip-path: inset(0 -4px 0 0); } }`,
    )
    return name
  }
  // A ring that blooms where a message lands.
  const ripple = (at: number) => {
    const name = `r${id++}`
    css.push(
      `.${name} { animation-name: ${name}; animation-timing-function: ease-out; opacity: 0; transform-box: fill-box; transform-origin: center; }
    @keyframes ${name} { 0%, ${at}% { opacity: 0; transform: scale(0.3); } ${at + 0.5}% { opacity: 0.9; } ${at + 5}%, 100% { opacity: 0; transform: scale(2.4); } }`,
    )
    return name
  }

  type Pt = { x: number; y: number }
  /*
   * A message in flight. A hairline connector draws itself across the gap between the
   * windows, a dot rides it, a small label names what is crossing, and a ring marks
   * where it lands. `go`..`land` are % of the loop.
   */
  const flight = (
    p: Pt,
    q: Pt,
    go: number,
    land: number,
    label: string,
    tone: string,
    marker: string,
  ) => {
    const c1 = { x: p.x + (q.x > p.x ? 70 : -70), y: p.y }
    const c2 = { x: q.x + (q.x > p.x ? -70 : 70), y: q.y }
    const d = `M${p.x} ${p.y}C${c1.x} ${c1.y} ${c2.x} ${c2.y} ${q.x} ${q.y}`
    const mid = {
      x: (p.x + 3 * c1.x + 3 * c2.x + q.x) / 8,
      y: (p.y + 3 * c1.y + 3 * c2.y + q.y) / 8,
    }
    const out = land + 3.5
    const line = `f${id++}`
    css.push(
      `.${line} { animation-name: ${line}; stroke-dasharray: 100; stroke-dashoffset: 100; opacity: 0; }
    @keyframes ${line} { 0%, ${go}% { stroke-dashoffset: 100; opacity: 0; } ${go + 0.4}% { opacity: 1; } ${land}% { stroke-dashoffset: 0; opacity: 1; } ${out}%, 100% { stroke-dashoffset: 0; opacity: 0; } }`,
    )
    const t = (n: number) => (n / 100).toFixed(4)
    const pw = Math.round(label.length * 6.9 + 30)
    return `<g>
      <path class="${line}" d="${d}" pathLength="100" fill="none" stroke="${tone}" stroke-width="1.5" stroke-linecap="round" marker-end="url(#${marker})"/>
      <circle class="${between(go, out)}" cx="${p.x}" cy="${p.y}" r="3" fill="${tone}"/>
      <g opacity="0">
        <animate attributeName="opacity" dur="${LOOP}s" repeatCount="indefinite" values="0;0;1;1;0;0" keyTimes="0;${t(go)};${t(go + 0.4)};${t(land)};${t(land + 0.6)};1"/>
        <animateMotion dur="${LOOP}s" repeatCount="indefinite" path="${d}" keyPoints="0;0;1;1" keyTimes="0;${t(go)};${t(land)};1" calcMode="spline" keySplines="0 0 1 1;0.5 0 0.2 1;0 0 1 1"/>
        <circle r="8" fill="${tone}" fill-opacity="0.18"/>
        <circle r="3.5" fill="${tone}"/>
      </g>
      <g class="${between(go, out)}">
        <rect x="${mid.x - pw / 2}" y="${mid.y - 40}" width="${pw}" height="24" rx="12" fill="${a.paper}" stroke="${dark ? '#3a3a3c' : a.hair}" filter="url(#lift)"/>
        <circle cx="${mid.x - pw / 2 + 13}" cy="${mid.y - 28}" r="3" fill="${tone}"/>
        <text x="${mid.x - pw / 2 + 22}" y="${mid.y - 23.5}" font-family="${SANS}" font-size="12.5" font-weight="500" fill="${a.ink}">${escapeXml(label)}</text>
      </g>
      <circle class="${ripple(land)}" cx="${q.x}" cy="${q.y}" r="6" fill="none" stroke="${tone}" stroke-width="1.5"/>
    </g>`
  }

  /* ── The terminal ── */
  const tx = PAD + 22 // text left
  const mono = `font-family="${MONO}" font-size="14"`
  const tline = (y: number, body: string, cls: string, fill = TERM.ink) =>
    `<text class="${cls}" x="${tx}" y="${y}" ${mono} fill="${fill}" xml:space="preserve">${body}</text>`
  const bullet = (y: number, text: string, cls: string, fill = TERM.ink) =>
    `<g class="${cls}"><circle cx="${tx + 4}" cy="${y - 5}" r="3.5" fill="${fill}"/><text x="${tx + 18}" y="${y}" ${mono} fill="${TERM.ink}" xml:space="preserve">${text}</text></g>`

  /* The terminal window: Claude Code's banner on top, `body` under it, the prompt box below. */
  const termFrame = (body: string, prompt = '') => `
  <g filter="url(#shadow)">
    <rect x="${PAD}" y="${TOP}" width="${TW}" height="${WH}" rx="12" fill="${TERM.bg}"/>
  </g>
  <g clip-path="url(#term)">
    <rect x="${PAD}" y="${TOP}" width="${TW}" height="38" fill="${TERM.bar}"/>
    <path d="M${PAD} ${TOP + 38.5}h${TW}" stroke="${TERM.line}"/>
    <circle cx="${PAD + 20}" cy="${TOP + 19}" r="6" fill="#ff5f57"/><circle cx="${PAD + 40}" cy="${TOP + 19}" r="6" fill="#febc2e"/><circle cx="${PAD + 60}" cy="${TOP + 19}" r="6" fill="#28c840"/>
    <text x="${PAD + 82}" y="${TOP + 24}" font-family="${MONO}" font-size="13" fill="${TERM.dim}">your agent's session</text>
    <g fill="${TERM.claude}">
      <rect x="${tx}" y="${TOP + 64}" width="34" height="9"/><rect x="${tx - 4}" y="${TOP + 73}" width="42" height="9"/>
      <rect x="${tx + 4}" y="${TOP + 82}" width="4" height="7"/><rect x="${tx + 12}" y="${TOP + 82}" width="4" height="7"/><rect x="${tx + 22}" y="${TOP + 82}" width="4" height="7"/><rect x="${tx + 30}" y="${TOP + 82}" width="4" height="7"/>
      <rect x="${tx + 6}" y="${TOP + 67}" width="4" height="4" fill="${TERM.bg}"/><rect x="${tx + 24}" y="${TOP + 67}" width="4" height="4" fill="${TERM.bg}"/>
    </g>
    <text x="${tx + 58}" y="${TOP + 74}" font-family="${MONO}" font-size="14" font-weight="700" fill="${TERM.ink}">Claude Code</text>
    <text x="${tx + 58}" y="${TOP + 94}" font-family="${MONO}" font-size="13" fill="${TERM.dim}">Opus 5 · ~/todo-app</text>
    ${body}
    <path d="M${tx - 8} ${TOP + WH - 92.5}h${TW - 28}M${tx - 8} ${TOP + WH - 46.5}h${TW - 28}" stroke="${TERM.line}"/>
    <text x="${tx}" y="${TOP + WH - 64}" ${mono} fill="${TERM.dim}">❯</text>
    ${prompt}
    <rect class="caret" x="${tx + 18}" y="${TOP + WH - 78}" width="8" height="18" fill="${TERM.ink}"/>
    <text x="${tx}" y="${TOP + WH - 22}" font-family="${MONO}" font-size="12.5" fill="${TERM.auto}">▸▸ auto mode on <tspan fill="${TERM.dim}">· 1 shell</tspan></text>
  </g>`

  const svg = (
    aria: string,
    body: string,
  ) => `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${escapeXml(aria)}">
  <!-- Generated by scripts/build-readme-art.ts. Edit there, then run pnpm readme:art. -->
  <style>
    * { animation-duration: ${LOOP}s; animation-iteration-count: infinite; animation-timing-function: ${EASE}; animation-fill-mode: both; }
    .s-on { opacity: 1; }
    .caret { animation: caret 1.1s steps(1, end) infinite; }
    @keyframes caret { 50% { opacity: 0; } }
    .dots circle { animation: dot 1s ease-in-out infinite; }
    .dots circle:nth-child(2) { animation-delay: 0.15s; }
    .dots circle:nth-child(3) { animation-delay: 0.3s; }
    @keyframes dot { 0%, 100% { opacity: 0.25; } 50% { opacity: 1; } }
    ${css.join('\n    ')}
  </style>
  <defs>
    <linearGradient id="stage" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${stage.from}"/><stop offset="1" stop-color="${stage.to}"/></linearGradient>
    <radialGradient id="glow" cx="0.55" cy="0.45" r="0.6"><stop offset="0" stop-color="${stage.glow}"/><stop offset="1" stop-color="${stage.glow}" stop-opacity="0"/></radialGradient>
    <pattern id="dots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="11" cy="11" r="1" fill="${stage.dot}"/></pattern>
    <filter id="shadow" x="-10%" y="-10%" width="120%" height="125%"><feDropShadow dx="0" dy="18" stdDeviation="20" flood-color="#000" flood-opacity="${dark ? 0.55 : 0.16}"/></filter>
    <filter id="lift" x="-20%" y="-60%" width="140%" height="240%"><feDropShadow dx="0" dy="3" stdDeviation="4" flood-color="#000" flood-opacity="${dark ? 0.5 : 0.1}"/></filter>
    <marker id="arrow-brand" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse" markerUnits="userSpaceOnUse"><path d="M2 1.5L8 5L2 8.5" fill="none" stroke="${a.brand}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></marker>
    <marker id="arrow-amber" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse" markerUnits="userSpaceOnUse"><path d="M2 1.5L8 5L2 8.5" fill="none" stroke="${amber}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></marker>
    <clipPath id="frame"><rect width="${W}" height="${H}" rx="18"/></clipPath>
    <clipPath id="term"><rect x="${PAD}" y="${TOP}" width="${TW}" height="${WH}" rx="12"/></clipPath>
    <clipPath id="review"><rect x="${RX}" y="${TOP}" width="${RW}" height="${WH}" rx="12"/></clipPath>
  </defs>
  <g clip-path="url(#frame)">
    <rect width="${W}" height="${H}" fill="url(#stage)"/>
    <rect width="${W}" height="${H}" fill="url(#dots)"/>
    <rect width="${W}" height="${H}" fill="url(#glow)"/>
    ${body}
  </g>
</svg>
`

  return {
    W,
    H,
    PAD,
    TW,
    RX,
    RW,
    TOP,
    WH,
    css,
    nextId,
    show,
    between,
    type,
    ripple,
    flight,
    tx,
    mono,
    tline,
    bullet,
    termFrame,
    amber,
    svg,
  }
}

function demo(a: App, dark: boolean) {
  const {
    PAD,
    TW,
    RX,
    RW,
    TOP,
    WH,
    css,
    show,
    between,
    type,
    flight,
    tx,
    mono,
    tline,
    bullet,
    termFrame,
    amber,
    svg,
    nextId,
  } = kit(a, dark)

  // The session's timeline, in % of the loop.
  const T = {
    typeFrom: 2,
    typeTo: 6.5,
    sent: 7,
    ran: 8.5,
    open: 10,
    url: 11,
    p1: [12.5, 17] as const, // the review opens
    listen: [18, 40.5] as const,
    p2: [39.5, 44] as const, // your question
    poll: 44.5,
    think: 47,
    update: 50,
    diff: 52,
    p3: [55, 60] as const, // answer + fix
    answered: 61,
    listen2: 63,
  }
  // The review's timeline.
  const R = {
    land: 18.5,
    focus: 25,
    threadA: 26,
    typeFrom: 28,
    typeTo: 38,
    sent: 39.5,
    threadB: 44,
    working: [44, 59] as const,
    answer: 60.5,
    fix: 62.5,
  }

  const term = termFrame(
    `
    ${bullet(TOP + 136, 'Due dates now parse in plain words:', 's-on')}
    ${tline(TOP + 157, '  today, tomorrow, in N days, weekdays.', 's-on')}
    ${tline(TOP + 182, '  Edited 2 files · tests pass', 's-on', TERM.dim)}

    <g class="${show(T.sent, 'none')}">
      <rect x="${tx - 8}" y="${TOP + 206}" width="${TW - 28}" height="26" fill="${TERM.promptBg}"/>
      <text x="${tx}" y="${TOP + 224}" ${mono} fill="${TERM.dim}">❯ <tspan fill="${TERM.ink}" font-weight="700">/diffo</tspan></text>
    </g>
    ${tline(TOP + 258, '  Ran 3 shell commands', show(T.ran), TERM.dim)}
    ${bullet(TOP + 288, 'Review is open. I’m listening.', show(T.open))}
    <text class="${show(T.url)}" x="${tx + 18}" y="${TOP + 310}" ${mono} fill="${TERM.link}" text-decoration="underline">http://localhost:4949</text>

    <text class="${between(T.listen[0], T.listen[1])}" x="${tx}" y="${TOP + 344}" ${mono} fill="${TERM.claude}">✻ Listening for your comments…</text>
    <g class="${show(T.poll)}">
      <circle cx="${tx + 4}" cy="${TOP + 339}" r="3.5" fill="${TERM.ink}"/>
      <text x="${tx + 18}" y="${TOP + 344}" ${mono} fill="${TERM.ink}">diffo poll <tspan fill="${TERM.dim}">→ 1 question, dates.ts:14</tspan></text>
    </g>
    ${bullet(TOP + 376, 'Same-day weekday should roll a week.', show(T.think))}
    ${tline(TOP + 398, '  Fixing it, then answering.', show(T.think + 0.6), TERM.dim)}
    <g class="${show(T.update)}">
      <circle cx="${tx + 4}" cy="${TOP + 425}" r="3.5" fill="${TERM.add}"/>
      <text x="${tx + 18}" y="${TOP + 430}" ${mono} fill="${TERM.ink}"><tspan font-weight="700">Update</tspan>(src/todo/dates.ts)</text>
    </g>
    <g class="${show(T.diff)}">
      <rect x="${tx + 14}" y="${TOP + 440}" width="${TW - 60}" height="24" rx="3" fill="${TERM.addBg}"/>
      <text x="${tx + 20}" y="${TOP + 457}" font-family="${MONO}" font-size="13" fill="${TERM.add}" xml:space="preserve">15 + if (day === today()) return nextWeek(day)</text>
    </g>
    ${bullet(TOP + 494, 'Answered in your thread; the fix is', show(T.answered), TERM.add)}
    ${tline(TOP + 516, '  in the diff you’re reading.', show(T.answered + 0.4))}
    <text class="${show(T.listen2)}" x="${tx}" y="${TOP + 550}" ${mono} fill="${TERM.claude}">✻ Listening for your comments…</text>

`,
    `<text class="${type(T.typeFrom, T.typeTo, 6)} ${between(0, T.sent - 1)}" x="${tx + 18}" y="${TOP + WH - 64}" ${mono} fill="${TERM.ink}">/diffo</text>`,
  )

  /* ── The review ── */
  const X = RX + 18 // file card left
  const XR = RX + RW - 18
  const ROW = 28
  const HEAD = 52
  const CODE_TOP = TOP + HEAD + 46 + 46 + 10 // bar + file header
  const THREAD = CODE_TOP + 4 * ROW + 8
  const A_H = 104
  const B_H = 138
  const AFTER = THREAD + A_H + B_H + 10

  const tone = (k: Seg[0]) => (k === 'k' ? a.k : k === 'f' ? a.f : k === 'n' ? a.n : a.ink)
  const code = (segs: Seg[]) =>
    segs.map(([k, s]) => `<tspan fill="${tone(k)}">${escapeXml(s)}</tspan>`).join('')
  const row = (
    y: number,
    o: number | '',
    n: number | '',
    segs: Seg[],
    kind?: 'add' | 'del',
    cls = '',
  ) => {
    const bg = kind === 'add' ? a.addRow : kind === 'del' ? a.delRow : 'none'
    const sign = kind === 'add' ? '+' : kind === 'del' ? '−' : ''
    return `<g class="${cls}">
      <rect x="${X + 1}" y="${y}" width="${XR - X - 2}" height="${ROW}" fill="${bg}"/>
      ${kind === 'add' ? `<rect x="${X + 76}" y="${y}" width="2" height="${ROW}" fill="${a.add}"/>` : ''}
      <text x="${X + 32}" y="${y + 19}" text-anchor="end" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">${o}</text>
      <text x="${X + 68}" y="${y + 19}" text-anchor="end" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">${n}</text>
      <text x="${X + 90}" y="${y + 19}" text-anchor="middle" font-family="${MONO}" font-size="14" fill="${kind === 'add' ? a.add : a.del}">${sign}</text>
      <text x="${X + 104}" y="${y + 19}" font-family="${MONO}" font-size="13.5" xml:space="preserve">${code(segs)}</text>
    </g>`
  }
  const tick = (x: number, y: number, cls: string) => `<g class="${cls}">
      <rect x="${x}" y="${y}" width="14" height="14" rx="3.5" fill="${a.brand}"/>
      <path d="M${x + 3.2} ${y + 7.4}l2.8 2.8 4.8-5.4" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
    </g>`

  const QUESTION = 'Does “friday” on a Friday mean today or next week?'
  const viewed = `v${nextId()}`
  css.push(`.${viewed} { animation-name: ${viewed}; opacity: 0; }
    @keyframes ${viewed} { 0%, ${R.land + 3}% { opacity: 0; } ${R.land + 4}%, ${R.fix}% { opacity: 1; } ${R.fix + 1}%, 100% { opacity: 0; } }`)
  const shift = `l${nextId()}`
  css.push(`.${shift} { animation-name: ${shift}; }
    @keyframes ${shift} {
      0%, ${R.threadA}% { transform: translateY(${-(AFTER - THREAD + 8)}px); }
      ${R.threadA + 2}%, ${R.threadB}% { transform: translateY(${-(B_H + 10)}px); }
      ${R.threadB + 2}%, ${RESET}% { transform: none; }
      ${RESET + 3}%, 100% { transform: translateY(${-(AFTER - THREAD + 8)}px); }
    }`)
  const tail = `l${nextId()}`
  css.push(`.${tail} { animation-name: ${tail}; }
    @keyframes ${tail} { 0%, ${R.fix}% { transform: translateY(${-ROW}px); } ${R.fix + 2}%, ${RESET}% { transform: none; } ${RESET + 3}%, 100% { transform: translateY(${-ROW}px); } }`)
  const before = between(-1, R.fix)
  const after = show(R.fix, 'none')
  const working = between(R.working[0], R.working[1])
  const listening = `x${nextId()}`
  css.push(`.${listening} { animation-name: ${listening}; animation-timing-function: steps(1, end); }
    @keyframes ${listening} { 0%, ${R.working[0]}% { opacity: 1; } ${R.working[0] + 1}%, ${R.working[1]}% { opacity: 0; } ${R.working[1] + 1}%, 100% { opacity: 1; } }`)

  const lines = [
    [
      12,
      12,
      [
        ['k', 'export function '],
        ['f', 'parseDue'],
        ['', '(input: '],
        ['k', 'string'],
        ['', '): Date | '],
        ['k', 'null'],
        ['', ' {'],
      ],
    ],
    [
      13,
      '',
      [
        ['k', '  const '],
        ['', 'day = WEEKDAYS.'],
        ['f', 'indexOf'],
        ['', '(input.'],
        ['f', 'toLowerCase'],
        ['', '())'],
      ],
      'del',
    ],
    [
      '',
      13,
      [
        ['k', '  const '],
        ['', 'day = WEEKDAYS.'],
        ['f', 'indexOf'],
        ['', '('],
        ['f', 'normalize'],
        ['', '(input))'],
      ],
      'add',
    ],
    [
      14,
      14,
      [
        ['k', '  if '],
        ['', '(day === '],
        ['n', '-1'],
        ['', ') '],
        ['k', 'return null'],
      ],
    ],
  ] as Array<[number | '', number | '', Seg[], ('add' | 'del')?]>

  const review = `
  <!-- Before /diffo: an empty slot where the review will open -->
  <g class="${between(-1, T.p1[1])}">
    <rect x="${RX + 1}" y="${TOP + 1}" width="${RW - 2}" height="${WH - 2}" rx="12" fill="none" stroke="${a.ink3}" stroke-opacity="0.35" stroke-width="1.5" stroke-dasharray="6 8"/>
    <text x="${RX + RW / 2}" y="${TOP + WH / 2}" text-anchor="middle" font-family="${MONO}" font-size="14" fill="${a.ink3}">localhost:4949</text>
  </g>

  <g class="${show(T.p1[1] - 0.5, 'scale(0.97)')}" style="transform-origin: ${RX + RW / 2}px ${TOP + 120}px">
    <g filter="url(#shadow)"><rect x="${RX}" y="${TOP}" width="${RW}" height="${WH}" rx="12" fill="${a.paper}"/></g>
    <g clip-path="url(#review)" font-family="${SANS}">
      <!-- Header -->
      <path d="M${RX + 20} ${TOP + 21}h14M${RX + 20} ${TOP + 27}h10M${RX + 20} ${TOP + 33}h14" stroke="${a.ink}" stroke-width="1.8" stroke-linecap="round"/>
      <text x="${RX + 44}" y="${TOP + 33}" font-size="17" font-weight="600" fill="${a.ink}">Diffo</text>
      <text x="${RX + 102}" y="${TOP + 32}" font-family="${MONO}" font-size="13" fill="${a.ink}">working tree → HEAD</text>
      <rect x="${RX + RW - 292.5}" y="${TOP + 12.5}" width="152" height="28" rx="14" fill="${a.attnWash}" stroke="${a.attnLine}"/>
      <g fill="${a.attn}"><rect x="${RX + RW - 278}" y="${TOP + 24}" width="2" height="5" rx="1"/><rect x="${RX + RW - 274}" y="${TOP + 22}" width="2" height="9" rx="1"/><rect x="${RX + RW - 270}" y="${TOP + 24}" width="2" height="5" rx="1"/></g>
      <text class="${listening}" x="${RX + RW - 262}" y="${TOP + 31}" font-size="12.5" fill="${a.attn}">agent · listening</text>
      <text class="${working}" x="${RX + RW - 262}" y="${TOP + 31}" font-size="12.5" fill="${a.attn}">agent · working</text>
      <rect x="${RX + RW - 130}" y="${TOP + 11}" width="114" height="31" rx="15.5" fill="${a.finishBg}"/>
      <text x="${RX + RW - 73}" y="${TOP + 31}" text-anchor="middle" font-size="13" font-weight="600" fill="${a.finishFg}">Finish review</text>
      <path d="M${RX} ${TOP + HEAD + 0.5}h${RW}" stroke="${a.hair}"/>

      <rect x="${X}" y="${TOP + HEAD + 22}" width="56" height="2" rx="1" fill="${a.fill2}"/>
      <rect class="${viewed}" x="${X}" y="${TOP + HEAD + 22}" width="56" height="2" rx="1" fill="${a.brand}"/>
      <text x="${X + 70}" y="${TOP + HEAD + 28}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">layer 1 / 3 · 1 file</text>

      <!-- File card -->
      <g class="${show(R.land)}">
        <rect x="${X + 0.5}" y="${TOP + HEAD + 46.5}" width="${XR - X - 1}" height="${WH - HEAD - 66}" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
        <path d="M${X + 1} ${TOP + HEAD + 56}a9 9 0 0 1 9 -9H${XR - 10}a9 9 0 0 1 9 9V${TOP + HEAD + 92}H${X + 1}z" fill="${a.fill}"/>
        <path d="M${X} ${TOP + HEAD + 92.5}h${XR - X}" stroke="${a.hair}"/>
        <path d="M${X + 16} ${TOP + HEAD + 67}l4 4 4-4" fill="none" stroke="${a.ink3}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
        <text x="${X + 34}" y="${TOP + HEAD + 75}" font-family="${MONO}" font-size="13.5" fill="${a.ink3}">src/todo/<tspan font-weight="700" fill="${a.ink}">dates.ts</tspan></text>
        <g class="${show(R.fix + 0.5, 'translateY(-3px)')}">
          <rect x="${X + 190.5}" y="${TOP + HEAD + 58.5}" width="184" height="23" rx="11.5" fill="${a.attnWash}" stroke="${a.attnLine}"/>
          <text x="${X + 282.5}" y="${TOP + HEAD + 74}" text-anchor="middle" font-size="12.5" fill="${a.attn}">changed since you read it</text>
        </g>
        <rect x="${XR - 112.5}" y="${TOP + HEAD + 56.5}" width="98" height="27" rx="6" fill="${a.paper}" stroke="${a.hair}"/>
        <rect x="${XR - 101.5}" y="${TOP + HEAD + 63.5}" width="13" height="13" rx="3.5" fill="none" stroke="${a.ink3}"/>
        ${tick(XR - 102, TOP + HEAD + 63, viewed)}
        <text x="${XR - 80}" y="${TOP + HEAD + 75}" font-size="13" fill="${a.ink}">Viewed</text>
      </g>

      ${lines.map(([o, n, segs, kind], i) => row(CODE_TOP + i * ROW, o, n, segs, kind, show(R.land + 0.8 + i * 0.6))).join('\n      ')}
      <rect class="${between(R.focus, R.fix)}" x="${X + 1}" y="${CODE_TOP + 3 * ROW}" width="${XR - X - 2}" height="${ROW}" fill="${a.focus}"/>

      <!-- The thread: the agent's half first, so the comment card's corners sit under it -->
      <g class="${show(R.threadB)}">
        <path d="M${X + 14.5} ${THREAD + A_H - 12}V${THREAD + A_H + B_H - 10}a10 10 0 0 0 10 10H${XR - 24.5}a10 10 0 0 0 10 -10V${THREAD + A_H - 12}" fill="${a.paper}" stroke="${a.hair}"/>
        <rect x="${X + 15}" y="${THREAD + A_H - 12}" width="${XR - X - 30}" height="12" fill="${a.paper}"/>
        <path d="M${X + 15} ${THREAD + A_H + 0.5}h${XR - X - 30}" stroke="${a.hair}"/>
        <circle cx="${X + 40}" cy="${THREAD + A_H + 26}" r="12" fill="${a.attnWash}" stroke="${a.attnLine}"/>
        <text x="${X + 40}" y="${THREAD + A_H + 31}" text-anchor="middle" font-size="12" fill="${a.attn}">✦</text>
        <text x="${X + 62}" y="${THREAD + A_H + 24}" font-size="13" font-weight="600" fill="${a.attn}">Agent</text>
        <text class="${between(R.threadB, R.answer)}" x="${X + 106}" y="${THREAD + A_H + 24}" font-size="13" fill="${a.ink3}">with the agent · just now</text>
        <text class="${show(R.answer, 'none')}" x="${X + 106}" y="${THREAD + A_H + 24}" font-size="13" fill="${a.ink3}">answered in 4.2s</text>
        <g class="${between(R.threadB, R.answer)} dots" fill="${a.ink3}"><circle cx="${X + 66}" cy="${THREAD + A_H + 46}" r="3"/><circle cx="${X + 77}" cy="${THREAD + A_H + 46}" r="3"/><circle cx="${X + 88}" cy="${THREAD + A_H + 46}" r="3"/></g>
        <g class="${show(R.answer)}" font-size="14" fill="${a.ink}">
          <text x="${X + 62}" y="${THREAD + A_H + 47}">Today, which is wrong: a bare weekday means the next one.</text>
          <text x="${X + 62}" y="${THREAD + A_H + 69}">Fixed, so <tspan font-family="${MONO}" font-size="13" fill="${a.ink2}">parseDue('friday')</tspan> on a Friday rolls a week.</text>
        </g>
        <path d="M${X + 15} ${THREAD + A_H + 84.5}h${XR - X - 30}" stroke="${a.hair}"/>
        <rect x="${X + 28.5}" y="${THREAD + A_H + 96.5}" width="${XR - X - 150}" height="30" rx="7" fill="${a.paper}" stroke="${a.hair}"/>
        <text x="${X + 42}" y="${THREAD + A_H + 116}" font-size="13" fill="${a.ink3}">Reply…</text>
        <text x="${XR - 84}" y="${THREAD + A_H + 116}" font-size="13" fill="${a.ink2}">Resolve</text>
      </g>
      <g class="${show(R.threadA)}">
        <rect x="${X + 14.5}" y="${THREAD + 0.5}" width="${XR - X - 29}" height="${A_H}" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
        <path d="M${X + 15} ${THREAD + 36}V${THREAD + 10}a10 10 0 0 1 10 -10H${XR - 25}a10 10 0 0 1 10 10V${THREAD + 36}z" fill="${a.fill}"/>
        <path d="M${X + 15} ${THREAD + 36.5}h${XR - X - 30}" stroke="${a.hair}"/>
        <path d="M${X + 30} ${THREAD + 16}l3.5 3.5 3.5-3.5" fill="none" stroke="${a.ink3}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <text x="${X + 46}" y="${THREAD + 23}" font-size="13" fill="${a.ink2}">Comment on line 14</text>
        <rect x="${X + 176.5}" y="${THREAD + 8.5}" width="70" height="20" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
        <text x="${X + 211.5}" y="${THREAD + 22.5}" text-anchor="middle" font-size="12" fill="${a.ink}">Question</text>
        <text class="${between(-1, R.sent)}" x="${XR - 34}" y="${THREAD + 23}" text-anchor="end" font-size="12.5" fill="${a.ink3}">Draft</text>
        <text class="${show(R.sent, 'none')}" x="${XR - 34}" y="${THREAD + 23}" text-anchor="end" font-size="12.5" fill="${a.ink3}">Sent</text>
        <circle cx="${X + 40}" cy="${THREAD + 62}" r="12" fill="${a.ink}"/>
        <text x="${X + 62}" y="${THREAD + 60}" font-size="13" fill="${a.ink3}"><tspan font-weight="600" fill="${a.ink}">You</tspan>  commented just now</text>
        <text class="${type(R.typeFrom, R.typeTo, QUESTION.length)}" x="${X + 62}" y="${THREAD + 83}" font-size="14.5" fill="${a.ink}">${QUESTION}</text>
      </g>

      <g class="${shift}">
        <g class="${show(R.fix)}">${row(
          AFTER,
          '',
          15,
          [
            ['k', '  if '],
            ['', '(day === '],
            ['f', 'today'],
            ['', '()) '],
            ['k', 'return '],
            ['f', 'nextWeek'],
            ['', '(day)'],
          ],
          'add',
        )}</g>
        <g class="${tail}">
          <g class="${before}">${row(
            AFTER + ROW,
            15,
            15,
            [
              ['k', '  return '],
              ['f', 'nextWeekday'],
              ['', '(day)'],
            ],
            undefined,
            show(R.land + 3.2),
          )}${row(AFTER + 2 * ROW, 16, 16, [['', '}']], undefined, show(R.land + 3.8))}</g>
          <g class="${after}">${row(AFTER + ROW, 15, 16, [
            ['k', '  return '],
            ['f', 'nextWeekday'],
            ['', '(day)'],
          ])}${row(AFTER + 2 * ROW, 16, 17, [['', '}']])}</g>
        </g>
      </g>
    </g>
    <rect x="${RX + 0.5}" y="${TOP + 0.5}" width="${RW - 1}" height="${WH - 1}" rx="11.5" fill="none" stroke="${a.hair}"/>
  </g>`

  /* ── The messages ── */
  // Each runs edge to edge through the gap between the windows, never across the text.
  const termEdge = PAD + TW - 10
  const reviewEdge = X + 6
  const flights = `
  ${flight({ x: tx + 200, y: TOP + 305 }, { x: RX + 18, y: TOP + 150 }, T.p1[0], T.p1[1], 'opens the review', a.brand, 'arrow-brand')}
  ${flight({ x: reviewEdge, y: THREAD + 78 }, { x: termEdge, y: TOP + 339 }, T.p2[0], T.p2[1], 'Question · line 14', amber, 'arrow-amber')}
  ${flight({ x: termEdge, y: TOP + 452 }, { x: reviewEdge, y: AFTER + 14 }, T.p3[0], T.p3[1], 'answer + fix', a.brand, 'arrow-brand')}`

  return svg(
    "The Diffo loop: in the agent's terminal you type /diffo and the review opens; your question on line 14 flies to the agent, which fixes the code and answers; the answer and the fix fly back and land in the thread and the diff",
    `${term}\n    ${review}\n    ${flights}`,
  )
}

/* ── Layers: the change as ordered steps ──────────────────────────────── */

/*
 * The agent suggests layers, you accept, and it outlines the change from its own
 * session: the request crosses to the terminal, `diffo layers` posts the outline, and
 * four layers land in the rail. The first layer's card draws its diagram, its files are
 * read and ticked, and `]` steps to the next layer, twice.
 */
function layers(a: App, dark: boolean) {
  const {
    RX,
    RW,
    PAD,
    TW,
    TOP,
    WH,
    css,
    nextId,
    show,
    between,
    flight,
    tx,
    mono,
    tline,
    bullet,
    termFrame,
    amber,
    svg,
  } = kit(a, dark)

  // The scene's clock, in % of the loop.
  const C = {
    cursorIn: 2,
    click: 7,
    ask: [8.5, 13] as const, // the request crosses to the agent
    poll: 13.5,
    outline: 16,
    post: 19.5,
    posted: 22,
    land: [22.5, 27] as const, // four layers cross back
    rail: 27.5,
    card1: 29,
    up: 31,
    files1: 31,
    read1: [38, 40] as const,
    done1: 42,
    key1: 43.5,
    card2: 45.5,
    read2: [53, 55] as const,
    done2: 57,
    key2: 58.5,
    card3: 60.5,
  }

  const HEAD = 52
  const RAIL = 214
  const PX = RX + RAIL + 16 // pane left
  const PR = RX + RW - 16 // pane right

  /* ── terminal ── */
  const term = termFrame(`
    ${bullet(TOP + 136, 'Recurring todos are in: rules, parsing,', 's-on')}
    ${tline(TOP + 157, '  storage and tests, across 13 files.', 's-on')}
    ${tline(TOP + 182, '  Edited 13 files · tests pass', 's-on', TERM.dim)}
    <rect x="${tx - 8}" y="${TOP + 206}" width="${TW - 28}" height="26" fill="${TERM.promptBg}"/>
    <text x="${tx}" y="${TOP + 224}" ${mono} fill="${TERM.dim}">❯ <tspan fill="${TERM.ink}" font-weight="700">/diffo</tspan></text>
    ${tline(TOP + 258, '  Ran 3 shell commands', 's-on', TERM.dim)}
    ${bullet(TOP + 288, 'Review is open. I’m listening.', 's-on')}
    <text x="${tx + 18}" y="${TOP + 310}" ${mono} fill="${TERM.link}" text-decoration="underline">http://localhost:4949</text>

    <text class="${between(-1, C.poll - 0.5)}" x="${tx}" y="${TOP + 344}" ${mono} fill="${TERM.claude}">✻ Listening for your comments…</text>
    <g class="${show(C.poll)}">
      <circle cx="${tx + 4}" cy="${TOP + 339}" r="3.5" fill="${TERM.ink}"/>
      <text x="${tx + 18}" y="${TOP + 344}" ${mono} fill="${TERM.ink}">diffo poll <tspan fill="${TERM.dim}">→ you asked for layers</tspan></text>
    </g>
    ${bullet(TOP + 376, 'Outlining 13 files as 4 steps,', show(C.outline))}
    ${tline(TOP + 398, '  in the order to read them.', show(C.outline + 0.6), TERM.dim)}
    <g class="${show(C.post)}">
      <circle cx="${tx + 4}" cy="${TOP + 425}" r="3.5" fill="${TERM.add}"/>
      <text x="${tx + 18}" y="${TOP + 430}" ${mono} fill="${TERM.ink}"><tspan font-weight="700">Bash</tspan>(diffo layers --stdin)</text>
    </g>
    ${tline(TOP + 452, '  ⎿ posted 4 layers', show(C.posted), TERM.add)}
    ${bullet(TOP + 494, 'Layers are up. Start with the', show(C.up))}
    ${tline(TOP + 516, '  recurrence rule.', show(C.up + 0.4))}
    <text class="${show(C.up + 3)}" x="${tx}" y="${TOP + 550}" ${mono} fill="${TERM.claude}">✻ Listening for your comments…</text>`)

  /* ── review ── */
  const tick = (x: number, y: number, cls: string) => `<g class="${cls}">
      <rect x="${x}" y="${y}" width="14" height="14" rx="3.5" fill="${a.brand}"/>
      <path d="M${x + 3.2} ${y + 7.4}l2.8 2.8 4.8-5.4" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
    </g>`
  const box = (x: number, y: number) =>
    `<rect x="${x + 0.5}" y="${y + 0.5}" width="13" height="13" rx="3.5" fill="none" stroke="${a.ink3}"/>`
  // A one-off keyframe, for the few things that move rather than fade.
  const keyframes = (body: string) => {
    const name = `k${nextId()}`
    css.push(`.${name} { animation-name: ${name}; }\n    @keyframes ${name} { ${body} }`)
    return name
  }

  const L = [
    {
      title: 'The recurrence rule',
      sum: [
        'Everything hangs off recurrence.ts: a Rule is daily,',
        'weekly, or every n days, and nextOccurrence dates it.',
      ],
      flow: ['Todo', 'repeat', 'Rule', 'dueAt'],
      files: [
        ['src/model/', 'recurrence.ts', 'added', '+28', ''],
        ['src/model/', 'todo.ts', '', '+6', '−2'],
      ],
    },
    {
      title: 'Parsing “every …”',
      sum: [
        'parseRepeat reads “every monday” or “every 3 days”',
        'into a Rule; anything else is a 400.',
      ],
      flow: ['input', 'parseRepeat', 'Rule'],
      files: [
        ['src/parse/', 'repeat.ts', 'added', '+41', ''],
        ['src/', 'routes.ts', '', '+9', '−1'],
      ],
    },
    {
      title: 'Storage: a repeat column',
      sum: ['A repeat column on todos, written on create and', 'read back on list.'],
      flow: ['create', 'todos.repeat', 'list'],
      files: [
        ['db/migrations/', '004_repeat.sql', 'added', '+3', ''],
        ['src/', 'db.ts', '', '+12', '−2'],
        ['src/', 'store.ts', '', '+5', '−1'],
      ],
    },
    { title: 'Tests', sum: [], flow: [], files: [] },
  ]
  const counts = [2, 2, 3, 6]

  // A folded file, as a row: chevron, path, status, counts, Viewed.
  const fileRow = (
    y: number,
    [dir, name, status, plus, minus]: string[],
    viewedAt?: number,
    until?: number,
  ) => {
    const w = (dir.length + name.length) * 7.6
    return `
      <rect x="${PX + 0.5}" y="${y + 0.5}" width="${PR - PX - 1}" height="38" rx="8" fill="${a.fill}" stroke="${a.hair}"/>
      <path d="M${PX + 14} ${y + 15}l4 4.5-4 4.5" fill="none" stroke="${a.ink3}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
      <text x="${PX + 30}" y="${y + 24}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">${dir}<tspan font-weight="700" fill="${a.ink}">${name}</tspan></text>
      ${status ? `<text x="${PX + 38 + w}" y="${y + 24}" font-family="${SANS}" font-size="12" fill="${a.add}">${status}</text>` : ''}
      <text x="${PR - 108}" y="${y + 24}" text-anchor="end" font-family="${MONO}" font-size="12"><tspan fill="${a.add}">${plus}</tspan>${minus ? ` <tspan fill="${a.del}">${minus}</tspan>` : ''}</text>
      <rect x="${PR - 94.5}" y="${y + 7.5}" width="84" height="23" rx="6" fill="${a.paper}" stroke="${a.hair}"/>
      ${box(PR - 86, y + 12)}
      ${viewedAt !== undefined ? tick(PR - 86, y + 12, until ? between(viewedAt, until) : show(viewedAt, 'scale(0.6)')) : ''}
      <text x="${PR - 66}" y="${y + 24}" font-family="${SANS}" font-size="12.5" fill="${a.ink}">Viewed</text>`
  }

  // The layer card, then its files under it.
  const cardTop = TOP + HEAD + 50
  const layerView = (
    i: number,
    from: number,
    to: number | null,
    readAt: readonly [number, number],
  ) => {
    const l = L[i]
    const flowW = PR - PX - 32
    const n = l.flow.length
    const boxW = Math.min(100, (flowW - (n - 1) * 26) / n)
    const span = n * boxW + (n - 1) * 26
    const fx0 = PX + 16 + (flowW - span) / 2
    const nodes = l.flow
      .map((label, j) => {
        const x = fx0 + j * (boxW + 26)
        const y = cardTop + 112
        const edge =
          j < n - 1
            ? `<g class="${show(from + 1.2 + j * 0.6, 'none')}"><path d="M${x + boxW + 3} ${y + 13}h18" stroke="${a.ink3}" stroke-width="1.2"/><path d="M${x + boxW + 17} ${y + 9.5}l4.5 3.5-4.5 3.5" fill="none" stroke="${a.ink3}" stroke-width="1.2"/></g>`
            : ''
        return `<g class="${show(from + 0.8 + j * 0.6)}">
          <rect x="${x + 0.5}" y="${y + 0.5}" width="${boxW}" height="26" rx="4" fill="${a.paper}" stroke="${a.hair}"/>
          <text x="${x + boxW / 2}" y="${y + 17.5}" text-anchor="middle" font-family="${MONO}" font-size="11.5" fill="${a.ink}">${escapeXml(label)}</text>
        </g>${edge}`
      })
      .join('')
    const filesTop = cardTop + 172
    const rows = l.files
      .map(
        (f, j) =>
          `<g class="${show(from + 2 + j * 0.5)}">${fileRow(filesTop + j * 46, f, readAt[0] + j * (readAt[1] - readAt[0]))}</g>`,
      )
      .join('')
    return `<g class="${to === null ? show(from, 'translateX(10px)') : between(from, to)}">
      <rect x="${PX + 0.5}" y="${cardTop + 0.5}" width="${PR - PX - 1}" height="158" rx="10" fill="${a.paper}" stroke="${a.hair}"/>
      <text x="${PX + 16}" y="${cardTop + 24}" font-family="${SANS}" font-size="11.5" fill="${a.ink3}">Layer ${i + 1} of 4</text>
      <text x="${PX + 16}" y="${cardTop + 50}" font-family="${SANS}" font-size="18" font-weight="600" letter-spacing="-0.2" fill="${a.ink}">${escapeXml(l.title)}</text>
      <text x="${PX + 16}" y="${cardTop + 74}" font-family="${SANS}" font-size="13" fill="${a.ink2}">${escapeXml(l.sum[0])}</text>
      <text x="${PX + 16}" y="${cardTop + 93}" font-family="${SANS}" font-size="13" fill="${a.ink2}">${escapeXml(l.sum[1])}</text>
      <rect x="${PX + 12}" y="${cardTop + 104}" width="${PR - PX - 24}" height="42" rx="6" fill="${a.fill}"/>
      ${nodes}
      ${rows}
    </g>`
  }

  // Before the outline: every file, alphabetically.
  const alpha = [
    ['db/migrations/', '004_repeat.sql', 'added', '+3', ''],
    ['src/', 'cli.ts', '', '+4', '−1'],
    ['src/', 'db.ts', '', '+12', '−2'],
    ['src/model/', 'recurrence.ts', 'added', '+28', ''],
    ['src/model/', 'todo.ts', '', '+6', '−2'],
    ['src/parse/', 'repeat.ts', 'added', '+41', ''],
    ['src/', 'routes.ts', '', '+9', '−1'],
    ['src/', 'store.ts', '', '+5', '−1'],
    ['test/', 'recurrence.test.ts', 'added', '+64', ''],
    ['test/', 'repeat.test.ts', 'added', '+52', ''],
  ]
  const alphaList = alpha.map((f, j) => fileRow(TOP + HEAD + 50 + j * 46, f)).join('')

  // The rail: the files first, then the layers.
  const railRow = (i: number) => TOP + HEAD + 56 + i * 52
  const railFiles = alpha
    .map(
      ([, name], j) =>
        `<text x="${RX + 20}" y="${TOP + HEAD + 74 + j * 26}" font-family="${MONO}" font-size="12" fill="${a.ink2}">${escapeXml(name)}</text>`,
    )
    .join('')
  const railLayers = L.map((l, i) => {
    const y = railRow(i)
    const doneAt = [C.done1, C.done2][i]
    return `<g class="${show(C.rail + i * 0.5, 'translateX(-8px)')}">
      ${box(RX + 14, y + 4)}
      ${doneAt ? tick(RX + 14, y + 4, show(doneAt, 'scale(0.6)')) : ''}
      <text x="${RX + 38}" y="${y + 16}" font-family="${SANS}" font-size="13" font-weight="500" fill="${a.ink}">${escapeXml(l.title)}</text>
      <rect x="${RX + 38}" y="${y + 26}" width="40" height="2" rx="1" fill="${a.fill2}"/>
      ${doneAt ? `<rect class="${show(doneAt, 'none')}" x="${RX + 38}" y="${y + 26}" width="40" height="2" rx="1" fill="${a.brand}"/>` : ''}
      <text x="${RX + 86}" y="${y + 30}" font-family="${SANS}" font-size="11.5" fill="${a.ink3}">${counts[i]} files</text>
    </g>`
  }).join('')
  const cursorRow = keyframes(
    `0%, ${C.rail}% { opacity: 0; transform: none; } ${C.rail + 1}%, ${C.card2 - 1}% { opacity: 1; transform: none; } ${C.card2}%, ${C.card3 - 1}% { opacity: 1; transform: translateY(52px); } ${C.card3}%, ${RESET}% { opacity: 1; transform: translateY(104px); } ${RESET + 3}%, 100% { opacity: 0; transform: translateY(104px); }`,
  )
  const tabs = ['Files 13', 'Threads 0', 'Layers 4']
  const tabW = (RAIL - 20) / 3
  const tabKnob = keyframes(
    `0%, ${C.rail - 1}% { transform: none; } ${C.rail}%, ${RESET}% { transform: translateX(${tabW * 2}px); } ${RESET + 3}%, 100% { transform: none; }`,
  )

  // The header chip: it suggests layers and pulses until clicked, then works, then listens.
  const pulse = keyframes(
    `0%, ${C.click}% { opacity: 0.7; transform: scale(1); } ${C.click + 0.1}%, 100% { opacity: 0; transform: scale(1); }`,
  )
  css.push(`.halo { animation: halo 1.4s ease-out infinite; transform-box: fill-box; transform-origin: center; }
    @keyframes halo { from { opacity: 0.6; transform: scale(1); } to { opacity: 0; transform: scale(1.18, 1.5); } }`)
  const chipX = RX + RW - 300
  const chip = `
      <g class="${pulse}"><rect class="halo" x="${chipX}" y="${TOP + 12}" width="168" height="29" rx="14.5" fill="none" stroke="${amber}" stroke-width="1.5"/></g>
      <rect x="${chipX + 0.5}" y="${TOP + 12.5}" width="168" height="28" rx="14" fill="${a.attnWash}" stroke="${a.attnLine}"/>
      <g fill="${a.attn}"><rect x="${chipX + 14}" y="${TOP + 24}" width="2" height="5" rx="1"/><rect x="${chipX + 18}" y="${TOP + 22}" width="2" height="9" rx="1"/><rect x="${chipX + 22}" y="${TOP + 24}" width="2" height="5" rx="1"/></g>
      <text class="${between(-1, C.click)}" x="${chipX + 32}" y="${TOP + 31}" font-family="${SANS}" font-size="12.5" fill="${a.attn}">agent · suggests layers</text>
      <text class="${between(C.click, C.land[1])}" x="${chipX + 32}" y="${TOP + 31}" font-family="${SANS}" font-size="12.5" fill="${a.attn}">agent · working</text>
      <text class="${show(C.land[1], 'none')}" x="${chipX + 32}" y="${TOP + 31}" font-family="${SANS}" font-size="12.5" fill="${a.attn}">agent · listening</text>`

  // The reviewer's pointer: in from below, onto the chip, a click.
  const cursorMove = keyframes(
    `0%, ${C.cursorIn}% { opacity: 0; transform: translate(-150px, 260px); } ${C.cursorIn + 1}% { opacity: 1; } ${C.click - 0.6}% { transform: none; } ${C.click}% { transform: scale(0.88); } ${C.click + 0.6}% { transform: none; opacity: 1; } ${C.click + 4}%, 100% { opacity: 0; transform: translate(20px, 40px); }`,
  )
  const pointer = `
    <g transform="translate(${chipX + 120} ${TOP + 22})">
      <g class="${cursorMove}">
        <path d="M0 0v17l4.4-4.1 3 6.6 2.7-1.2-3-6.5H13z" fill="${dark ? '#fff' : '#111'}" stroke="${dark ? '#000' : '#fff'}" stroke-width="1.2" stroke-linejoin="round"/>
      </g>
      <circle class="${show(C.click, 'scale(0.4)')} ${between(C.click, C.click + 2)}" r="12" fill="none" stroke="${amber}" stroke-width="1.5"/>
    </g>`

  // `]` steps to the next layer.
  const keycap = (at: number) => `
    <g class="${between(at - 1, at + 2.5)}">
      <rect x="${PR - 132.5}" y="${TOP + WH - 56.5}" width="30" height="30" rx="7" fill="${a.paper}" stroke="${a.hair}" stroke-width="1.5" filter="url(#lift)"/>
      <text x="${PR - 117.5}" y="${TOP + WH - 35.5}" text-anchor="middle" font-family="${MONO}" font-size="15" font-weight="700" fill="${a.ink}">]</text>
      <text x="${PR - 94}" y="${TOP + WH - 36}" font-family="${SANS}" font-size="13" fill="${a.ink2}">next layer</text>
    </g>`

  const review = `
  <g filter="url(#shadow)"><rect x="${RX}" y="${TOP}" width="${RW}" height="${WH}" rx="12" fill="${a.paper}"/></g>
  <g clip-path="url(#review)" font-family="${SANS}">
    <path d="M${RX + 20} ${TOP + 21}h14M${RX + 20} ${TOP + 27}h10M${RX + 20} ${TOP + 33}h14" stroke="${a.ink}" stroke-width="1.8" stroke-linecap="round"/>
    <text x="${RX + 44}" y="${TOP + 33}" font-size="17" font-weight="600" fill="${a.ink}">Diffo</text>
    <text x="${RX + 102}" y="${TOP + 32}" font-family="${MONO}" font-size="13" fill="${a.ink}">working tree → HEAD</text>
    ${chip}
    <rect x="${RX + RW - 124}" y="${TOP + 11}" width="110" height="31" rx="15.5" fill="${a.finishBg}"/>
    <text x="${RX + RW - 69}" y="${TOP + 31}" text-anchor="middle" font-size="13" font-weight="600" fill="${a.finishFg}">Finish review</text>
    <path d="M${RX} ${TOP + HEAD + 0.5}h${RW}" stroke="${a.hair}"/>

    <!-- Rail -->
    <path d="M${RX + RAIL + 0.5} ${TOP + HEAD}v${WH}" stroke="${a.hair}"/>
    <rect x="${RX + 10}" y="${TOP + HEAD + 10}" width="${RAIL - 20}" height="28" rx="7" fill="${a.fill}"/>
    <rect class="${tabKnob}" x="${RX + 12}" y="${TOP + HEAD + 12}" width="${tabW - 4}" height="24" rx="5.5" fill="${a.paper}"/>
    ${tabs.map((t, i) => `<text x="${RX + 10 + tabW * (i + 0.5)}" y="${TOP + HEAD + 28.5}" text-anchor="middle" font-size="12" fill="${a.ink2}">${t}</text>`).join('')}
    <g class="${between(-1, C.rail - 0.5)}">${railFiles}</g>
    <rect class="${cursorRow}" x="${RX}" y="${railRow(0) - 6}" width="${RAIL}" height="48" fill="${a.fill}"/>
    ${railLayers}

    <!-- Pane -->
    <g class="${between(-1, C.rail - 1)}">
      <text x="${PX}" y="${TOP + HEAD + 30}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">13 files · alphabetical</text>
      ${alphaList}
    </g>
    <g class="${show(C.rail, 'none')}">
      <text class="${between(C.rail, C.card2 - 1)}" x="${PX}" y="${TOP + HEAD + 30}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">layer 1 / 4 · 2 files</text>
      <text class="${between(C.card2 - 1, C.card3 - 1)}" x="${PX}" y="${TOP + HEAD + 30}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">layer 2 / 4 · 2 files</text>
      <text class="${show(C.card3 - 1, 'none')}" x="${PX}" y="${TOP + HEAD + 30}" font-family="${MONO}" font-size="12.5" fill="${a.ink3}">layer 3 / 4 · 3 files</text>
    </g>
    ${layerView(0, C.card1, C.card2 - 1, C.read1)}
    ${layerView(1, C.card2, C.card3 - 1, C.read2)}
    ${layerView(2, C.card3, null, [C.card3 + 20, C.card3 + 21])}
    ${keycap(C.key1)}
    ${keycap(C.key2)}
  </g>
  <rect x="${RX + 0.5}" y="${TOP + 0.5}" width="${RW - 1}" height="${WH - 1}" rx="11.5" fill="none" stroke="${a.hair}"/>
  ${pointer}`

  const flights = `
  ${flight({ x: RX + 8, y: TOP + 26 }, { x: PAD + TW - 10, y: TOP + 339 }, C.ask[0], C.ask[1], 'layers, please', amber, 'arrow-amber')}
  ${flight({ x: PAD + TW - 10, y: TOP + 447 }, { x: RX + 8, y: railRow(0) + 16 }, C.land[0], C.land[1], '4 layers', a.brand, 'arrow-brand')}`

  return svg(
    'Layers in Diffo: the header chip suggests layers and the reviewer accepts; the request crosses to the agent, which outlines the 13-file change as four ordered steps and posts them with diffo layers; the layers land in the rail, the first layer’s card draws its diagram, its files are read and ticked, and ] steps to the second and third layers.',
    `${term}\n    ${review}\n    ${flights}`,
  )
}

const root = join(import.meta.dirname, '..')
for (const [suffix, theme] of [
  ['', light],
  ['-dark', dark],
] as const) {
  const app = suffix ? appDark : appLight
  writeFileSync(join(root, 'assets', `readme-hero${suffix}.svg`), hero(theme))
  // The scenes live with the docs' clips, so the site and the README share one file.
  writeFileSync(join(root, 'docs/assets', `readme-demo${suffix}.svg`), demo(app, !!suffix))
  writeFileSync(join(root, 'docs/assets', `readme-layers${suffix}.svg`), layers(app, !!suffix))
}
console.log('wrote assets/readme-hero{,-dark}.svg and docs/assets/readme-{demo,layers}{,-dark}.svg')
